// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../public/sass/main.scss";
import "./globals.css";
import { NavBar, SideNav } from "@/components";

import { PomodoroProvider } from "@/store";

import { MusicProvider } from "@/store/contexts/music";
import { TodoProvider } from "@/store/contexts/todo/provider";
import { SessionProvider } from "@/store/contexts/session/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <PomodoroProvider>
        <SessionProvider>
          <TodoProvider>
            <MusicProvider>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <main className="app_layout">
                  <div className="app_layout_content">
                    <SideNav />
                    <div className="app_layout_content_main">
                      <NavBar />
                      {children}
                    </div>
                  </div>
                </main>
              </body>
            </MusicProvider>
          </TodoProvider>
        </SessionProvider>
      </PomodoroProvider>
    </html>
  );
}
